name: 03 - Runners de workflow 

on:
    push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Mostrar SO
              run: |
                echo "Este trabajo se ejecuta en un Runner de Ubuntu"
                echo "${{ runner.os }}"
    job2:
        runs-on: Windows-latest
        steps:
            - name: Mostrar SO
              run : |
                echo "Este trabajo se ejecuta en un Runner de Windows"
                echo "${{ runner.os }}"