name: 04 - Uso de Actions
on: push

jobs:
    job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
            
          - name: print structure folder
            run: echo tree